{
  "formatVersion": "1.1",
  "component": {
    "group": "com.periut",
    "module": "starac",
    "version": "1.2.1+mcb1.7.3+gen2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.lwjgl",
          "module": "lwjgl-bom",
          "version": {
            "requires": "3.4.0"
          },
          "excludes": [
            {
              "group": "org.lwjgl.lwjgl",
              "module": "*"
            }
          ],
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "version": {
            "requires": "3.4.0"
          },
          "excludes": [
            {
              "group": "org.lwjgl.lwjgl",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "version": {
            "requires": "3.4.0"
          },
          "excludes": [
            {
              "group": "org.lwjgl.lwjgl",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-openal",
          "version": {
            "requires": "3.4.0"
          },
          "excludes": [
            {
              "group": "org.lwjgl.lwjgl",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengl",
          "version": {
            "requires": "3.4.0"
          },
          "excludes": [
            {
              "group": "org.lwjgl.lwjgl",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "starac-1.2.1+mcb1.7.3+gen2.jar",
          "url": "starac-1.2.1+mcb1.7.3+gen2.jar",
          "size": 9263781,
          "sha512": "addb12a2af1073684bfc4ddb997e882e63b32e5992a658b4aa26746aa2a48eae961e47c736e1205f5b8482710c2bda1a080e1f6646f9eb9f3b00878f8cdaad78",
          "sha256": "80e2975888a6ac0ca6faada5ae344ec6f0eaa3f9f365273817960e72dd2d219b",
          "sha1": "5d0e3cc188b470b6abb689466d47d3defe77ef29",
          "md5": "1638e9bddba919af946a79770e8a5b91"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.lwjgl",
          "module": "lwjgl-bom",
          "version": {
            "requires": "3.4.0"
          },
          "excludes": [
            {
              "group": "org.lwjgl.lwjgl",
              "module": "*"
            }
          ],
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "version": {
            "requires": "3.4.0"
          },
          "excludes": [
            {
              "group": "org.lwjgl.lwjgl",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "version": {
            "requires": "3.4.0"
          },
          "excludes": [
            {
              "group": "org.lwjgl.lwjgl",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-openal",
          "version": {
            "requires": "3.4.0"
          },
          "excludes": [
            {
              "group": "org.lwjgl.lwjgl",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengl",
          "version": {
            "requires": "3.4.0"
          },
          "excludes": [
            {
              "group": "org.lwjgl.lwjgl",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "excludes": [
            {
              "group": "org.lwjgl.lwjgl",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "excludes": [
            {
              "group": "org.lwjgl.lwjgl",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-glfw",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-openal",
          "excludes": [
            {
              "group": "org.lwjgl.lwjgl",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-openal",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengl",
          "excludes": [
            {
              "group": "org.lwjgl.lwjgl",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-opengl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "excludes": [
            {
              "group": "org.lwjgl.lwjgl",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-windows"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "excludes": [
            {
              "group": "org.lwjgl.lwjgl",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-glfw",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-windows"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-openal",
          "excludes": [
            {
              "group": "org.lwjgl.lwjgl",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-openal",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-windows"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengl",
          "excludes": [
            {
              "group": "org.lwjgl.lwjgl",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-opengl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-windows"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "excludes": [
            {
              "group": "org.lwjgl.lwjgl",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-macos"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "excludes": [
            {
              "group": "org.lwjgl.lwjgl",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-glfw",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-macos"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-openal",
          "excludes": [
            {
              "group": "org.lwjgl.lwjgl",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-openal",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-macos"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengl",
          "excludes": [
            {
              "group": "org.lwjgl.lwjgl",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-opengl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-macos"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "excludes": [
            {
              "group": "org.lwjgl.lwjgl",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-windows-arm64"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "excludes": [
            {
              "group": "org.lwjgl.lwjgl",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-glfw",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-windows-arm64"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-openal",
          "excludes": [
            {
              "group": "org.lwjgl.lwjgl",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-openal",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-windows-arm64"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengl",
          "excludes": [
            {
              "group": "org.lwjgl.lwjgl",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-opengl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-windows-arm64"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "excludes": [
            {
              "group": "org.lwjgl.lwjgl",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-macos-arm64"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "excludes": [
            {
              "group": "org.lwjgl.lwjgl",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-glfw",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-macos-arm64"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-openal",
          "excludes": [
            {
              "group": "org.lwjgl.lwjgl",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-openal",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-macos-arm64"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengl",
          "excludes": [
            {
              "group": "org.lwjgl.lwjgl",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-opengl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-macos-arm64"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "excludes": [
            {
              "group": "org.lwjgl.lwjgl",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux-arm64"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "excludes": [
            {
              "group": "org.lwjgl.lwjgl",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-glfw",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux-arm64"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-openal",
          "excludes": [
            {
              "group": "org.lwjgl.lwjgl",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-openal",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux-arm64"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengl",
          "excludes": [
            {
              "group": "org.lwjgl.lwjgl",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-opengl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux-arm64"
            }
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          },
          "excludes": [
            {
              "group": "org.lwjgl.lwjgl",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "starac-1.2.1+mcb1.7.3+gen2.jar",
          "url": "starac-1.2.1+mcb1.7.3+gen2.jar",
          "size": 9263781,
          "sha512": "addb12a2af1073684bfc4ddb997e882e63b32e5992a658b4aa26746aa2a48eae961e47c736e1205f5b8482710c2bda1a080e1f6646f9eb9f3b00878f8cdaad78",
          "sha256": "80e2975888a6ac0ca6faada5ae344ec6f0eaa3f9f365273817960e72dd2d219b",
          "sha1": "5d0e3cc188b470b6abb689466d47d3defe77ef29",
          "md5": "1638e9bddba919af946a79770e8a5b91"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "starac-1.2.1+mcb1.7.3+gen2-sources.jar",
          "url": "starac-1.2.1+mcb1.7.3+gen2-sources.jar",
          "size": 361728,
          "sha512": "302bfaad837719144d1b9d5e1e8b63e577e6193f4313c086655fc3b1f76c3bb6de4fbda918c4d77de4f1cf7c2fe04e6b3077355ec0768c203c5ccfc10291fdc4",
          "sha256": "3d0cedefca3e4c0268e439c271e2aff9c86f129b19da808a26752cfe0dcab22d",
          "sha1": "936531d991f26966c9427bdb96db449e57b3e078",
          "md5": "d8eed005cae3ad9b90ee3dac23a16e05"
        }
      ]
    }
  ]
}
