{
  "formatVersion": "1.1",
  "component": {
    "group": "com.periut",
    "module": "starac",
    "version": "1.2.2+mcb1.7.3+gen2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.lwjgl",
          "module": "lwjgl-bom",
          "version": {
            "requires": "3.4.0"
          },
          "excludes": [
            {
              "group": "org.lwjgl.lwjgl",
              "module": "*"
            }
          ],
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "version": {
            "requires": "3.4.0"
          },
          "excludes": [
            {
              "group": "org.lwjgl.lwjgl",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "version": {
            "requires": "3.4.0"
          },
          "excludes": [
            {
              "group": "org.lwjgl.lwjgl",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-openal",
          "version": {
            "requires": "3.4.0"
          },
          "excludes": [
            {
              "group": "org.lwjgl.lwjgl",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengl",
          "version": {
            "requires": "3.4.0"
          },
          "excludes": [
            {
              "group": "org.lwjgl.lwjgl",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "starac-1.2.2+mcb1.7.3+gen2.jar",
          "url": "starac-1.2.2+mcb1.7.3+gen2.jar",
          "size": 9565681,
          "sha512": "8d6f9b7677abe52bcd87bfb290995f6d2a3da390357dc1459f0412dc86bb8ea28a974cf833c1f4bb8cef0c5445e1faf7804b1753a9f8958fc21cce778276f47b",
          "sha256": "9d9ef415d4016f3fc2c2b01019e6f00e996d3022f642de41b99b5fb4d065b283",
          "sha1": "7a828c551ff10b05fffb37ca25fb17ccc6f60346",
          "md5": "1e3d39e7bad497f6191ae2cc08a5b5a9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.lwjgl",
          "module": "lwjgl-bom",
          "version": {
            "requires": "3.4.0"
          },
          "excludes": [
            {
              "group": "org.lwjgl.lwjgl",
              "module": "*"
            }
          ],
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "version": {
            "requires": "3.4.0"
          },
          "excludes": [
            {
              "group": "org.lwjgl.lwjgl",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "version": {
            "requires": "3.4.0"
          },
          "excludes": [
            {
              "group": "org.lwjgl.lwjgl",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-openal",
          "version": {
            "requires": "3.4.0"
          },
          "excludes": [
            {
              "group": "org.lwjgl.lwjgl",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengl",
          "version": {
            "requires": "3.4.0"
          },
          "excludes": [
            {
              "group": "org.lwjgl.lwjgl",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "excludes": [
            {
              "group": "org.lwjgl.lwjgl",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "excludes": [
            {
              "group": "org.lwjgl.lwjgl",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-glfw",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-openal",
          "excludes": [
            {
              "group": "org.lwjgl.lwjgl",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-openal",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengl",
          "excludes": [
            {
              "group": "org.lwjgl.lwjgl",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-opengl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "excludes": [
            {
              "group": "org.lwjgl.lwjgl",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-windows"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "excludes": [
            {
              "group": "org.lwjgl.lwjgl",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-glfw",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-windows"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-openal",
          "excludes": [
            {
              "group": "org.lwjgl.lwjgl",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-openal",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-windows"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengl",
          "excludes": [
            {
              "group": "org.lwjgl.lwjgl",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-opengl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-windows"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "excludes": [
            {
              "group": "org.lwjgl.lwjgl",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-macos"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "excludes": [
            {
              "group": "org.lwjgl.lwjgl",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-glfw",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-macos"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-openal",
          "excludes": [
            {
              "group": "org.lwjgl.lwjgl",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-openal",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-macos"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengl",
          "excludes": [
            {
              "group": "org.lwjgl.lwjgl",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-opengl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-macos"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "excludes": [
            {
              "group": "org.lwjgl.lwjgl",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-windows-arm64"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "excludes": [
            {
              "group": "org.lwjgl.lwjgl",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-glfw",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-windows-arm64"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-openal",
          "excludes": [
            {
              "group": "org.lwjgl.lwjgl",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-openal",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-windows-arm64"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengl",
          "excludes": [
            {
              "group": "org.lwjgl.lwjgl",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-opengl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-windows-arm64"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "excludes": [
            {
              "group": "org.lwjgl.lwjgl",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-macos-arm64"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "excludes": [
            {
              "group": "org.lwjgl.lwjgl",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-glfw",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-macos-arm64"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-openal",
          "excludes": [
            {
              "group": "org.lwjgl.lwjgl",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-openal",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-macos-arm64"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengl",
          "excludes": [
            {
              "group": "org.lwjgl.lwjgl",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-opengl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-macos-arm64"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "excludes": [
            {
              "group": "org.lwjgl.lwjgl",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux-arm64"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "excludes": [
            {
              "group": "org.lwjgl.lwjgl",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-glfw",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux-arm64"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-openal",
          "excludes": [
            {
              "group": "org.lwjgl.lwjgl",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-openal",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux-arm64"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengl",
          "excludes": [
            {
              "group": "org.lwjgl.lwjgl",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-opengl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux-arm64"
            }
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.3"
          },
          "excludes": [
            {
              "group": "org.lwjgl.lwjgl",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.ornithemc.osl-gen2",
          "module": "localization",
          "version": {
            "requires": "0.1.0-alpha.4+mcb1.0-mc11w48a"
          },
          "excludes": [
            {
              "group": "org.lwjgl.lwjgl",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.ornithemc.osl-gen2",
          "module": "core",
          "version": {
            "requires": "0.8.0-alpha.4+mca1.0.1_01-mc14w26c"
          },
          "excludes": [
            {
              "group": "org.lwjgl.lwjgl",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.ornithemc.osl-gen2",
          "module": "networking-impl",
          "version": {
            "requires": "0.1.1+mcb1.5-mc11w48a"
          },
          "excludes": [
            {
              "group": "org.lwjgl.lwjgl",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.ornithemc.osl-gen2",
          "module": "keybinds",
          "version": {
            "requires": "0.2.0+mca1.0.1_01-mcb1.7.3"
          },
          "excludes": [
            {
              "group": "org.lwjgl.lwjgl",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.ornithemc.osl-gen2",
          "module": "branding",
          "version": {
            "requires": "0.4.3-alpha.1+mca1.2.2-mc14w29b"
          },
          "excludes": [
            {
              "group": "org.lwjgl.lwjgl",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.ornithemc.osl-gen2",
          "module": "text-components",
          "version": {
            "requires": "0.1.0-alpha.2+mca0.1.0-mc1.14.4"
          },
          "excludes": [
            {
              "group": "org.lwjgl.lwjgl",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.ornithemc.osl-gen2",
          "module": "executors",
          "version": {
            "requires": "0.1.0+mcin-20100128-2304-mcb1.9-pre2"
          },
          "excludes": [
            {
              "group": "org.lwjgl.lwjgl",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.ornithemc.osl-gen2",
          "module": "entrypoints",
          "version": {
            "requires": "0.6.0+mca1.0.1_01-mc1.5.2"
          },
          "excludes": [
            {
              "group": "org.lwjgl.lwjgl",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.ornithemc.osl-gen2",
          "module": "networking",
          "version": {
            "requires": "0.9.0+mcb1.0-mc13w39b"
          },
          "excludes": [
            {
              "group": "org.lwjgl.lwjgl",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.ornithemc.osl-gen2",
          "module": "lifecycle-events",
          "version": {
            "requires": "0.6.1-alpha.2+mcb1.3-mc12w17a"
          },
          "excludes": [
            {
              "group": "org.lwjgl.lwjgl",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.ornithemc.osl-gen2",
          "module": "config",
          "version": {
            "requires": "0.6.0+mcb1.3-mcb1.7.3"
          },
          "excludes": [
            {
              "group": "org.lwjgl.lwjgl",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.ornithemc.osl-gen2",
          "module": "resource-loader",
          "version": {
            "requires": "0.7.0-alpha.8+mca1.2.2-mc1.2.5"
          },
          "excludes": [
            {
              "group": "org.lwjgl.lwjgl",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "starac-1.2.2+mcb1.7.3+gen2.jar",
          "url": "starac-1.2.2+mcb1.7.3+gen2.jar",
          "size": 9565681,
          "sha512": "8d6f9b7677abe52bcd87bfb290995f6d2a3da390357dc1459f0412dc86bb8ea28a974cf833c1f4bb8cef0c5445e1faf7804b1753a9f8958fc21cce778276f47b",
          "sha256": "9d9ef415d4016f3fc2c2b01019e6f00e996d3022f642de41b99b5fb4d065b283",
          "sha1": "7a828c551ff10b05fffb37ca25fb17ccc6f60346",
          "md5": "1e3d39e7bad497f6191ae2cc08a5b5a9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "starac-1.2.2+mcb1.7.3+gen2-sources.jar",
          "url": "starac-1.2.2+mcb1.7.3+gen2-sources.jar",
          "size": 416732,
          "sha512": "e02ed1a45cb257b909c3ce1c34bb3f80cf202f29beb8f5e938fa41464cd27ba9ae68ca0addb09c56fc3cff30279893df2a3b35706c69e333f02dc6513dd1c49b",
          "sha256": "bb95d384a24fe875b540091d1381bc5fd839f833116d99d99d1ec139cf4c0e32",
          "sha1": "fbab9232b55f3038f036e8ebeaf81ea91efc8fe8",
          "md5": "99a106324a06823fa8390413d181cc60"
        }
      ]
    }
  ]
}
