{
  "formatVersion": "1.1",
  "component": {
    "group": "com.periut",
    "module": "retrocommands",
    "version": "0.7.3+gen2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.periut",
          "module": "accessory-api",
          "version": {
            "requires": "0.8.0+gen2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.periut",
          "module": "retroapi",
          "version": {
            "requires": "0.1.3"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "retrocommands-0.7.3+gen2.jar",
          "url": "retrocommands-0.7.3+gen2.jar",
          "size": 127540,
          "sha512": "f8e528be9544b1d4d428fab5ef0c5b2489dcd000a5a8ac38b78946fc156f997f644d600b27a4e0393bb8dcc6896d50bbc5752ecfeb188033c76f2e73e7f18535",
          "sha256": "d32275c41ff4b3ad95c3b92e95c89dfb84bca40041b472a9cc0ca6c4121c41d3",
          "sha1": "7c1b21706e0f3166450516794d2290799cba5ae5",
          "md5": "c5936fb9a04b3cd54db7aa4f610aed37"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.8.0-beta4"
          },
          "excludes": [
            {
              "group": "org.lwjgl.lwjgl",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-slf4j18-impl",
          "version": {
            "requires": "2.17.2"
          },
          "excludes": [
            {
              "group": "org.lwjgl.lwjgl",
              "module": "*"
            }
          ]
        },
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.2.2"
          },
          "excludes": [
            {
              "group": "org.lwjgl.lwjgl",
              "module": "*"
            }
          ]
        },
        {
          "group": "blue.endless",
          "module": "jankson",
          "version": {
            "requires": "1.2.1"
          },
          "excludes": [
            {
              "group": "org.lwjgl.lwjgl",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.2.1-jre"
          },
          "excludes": [
            {
              "group": "org.lwjgl.lwjgl",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.3"
          },
          "excludes": [
            {
              "group": "org.lwjgl.lwjgl",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.ornithemc.osl-gen2",
          "module": "core",
          "version": {
            "requires": "0.7.1"
          },
          "excludes": [
            {
              "group": "org.lwjgl.lwjgl",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.ornithemc.osl-gen2",
          "module": "networking-impl",
          "version": {
            "requires": "0.1.1+mcb1.5-mc11w48a"
          },
          "excludes": [
            {
              "group": "org.lwjgl.lwjgl",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.ornithemc.osl-gen2",
          "module": "keybinds",
          "version": {
            "requires": "0.2.0+mca1.0.1_01-mcb1.7.3"
          },
          "excludes": [
            {
              "group": "org.lwjgl.lwjgl",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.ornithemc.osl-gen2",
          "module": "branding",
          "version": {
            "requires": "0.4.2+mca1.2.2-mc14w29b"
          },
          "excludes": [
            {
              "group": "org.lwjgl.lwjgl",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.ornithemc.osl-gen2",
          "module": "text-components",
          "version": {
            "requires": "0.1.0-alpha.1+mca0.1.0-mc1.14.4"
          },
          "excludes": [
            {
              "group": "org.lwjgl.lwjgl",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.ornithemc.osl-gen2",
          "module": "executors",
          "version": {
            "requires": "0.1.0+mcin-20100128-2304-mcb1.9-pre2"
          },
          "excludes": [
            {
              "group": "org.lwjgl.lwjgl",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.ornithemc.osl-gen2",
          "module": "entrypoints",
          "version": {
            "requires": "0.6.0+mca1.0.1_01-mc1.5.2"
          },
          "excludes": [
            {
              "group": "org.lwjgl.lwjgl",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.ornithemc.osl-gen2",
          "module": "networking",
          "version": {
            "requires": "0.9.0+mcb1.0-mc13w39b"
          },
          "excludes": [
            {
              "group": "org.lwjgl.lwjgl",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.ornithemc.osl-gen2",
          "module": "lifecycle-events",
          "version": {
            "requires": "0.6.0+mcb1.3-mcb1.7.3"
          },
          "excludes": [
            {
              "group": "org.lwjgl.lwjgl",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.ornithemc.osl-gen2",
          "module": "config",
          "version": {
            "requires": "0.6.0+mcb1.3-mcb1.7.3"
          },
          "excludes": [
            {
              "group": "org.lwjgl.lwjgl",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.ornithemc.osl-gen2",
          "module": "resource-loader",
          "version": {
            "requires": "0.6.1+mca1.2.2-mc11w48a"
          },
          "excludes": [
            {
              "group": "org.lwjgl.lwjgl",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.periut.cryonicconfig",
          "module": "cryonicconfig-ornithe",
          "version": {
            "requires": "1.0.0+gen2+mcb1.7.3"
          },
          "excludes": [
            {
              "group": "org.lwjgl.lwjgl",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.periut",
          "module": "starac",
          "version": {
            "requires": "1.2.1+mcb1.7.3+gen2"
          },
          "excludes": [
            {
              "group": "org.lwjgl.lwjgl",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.github.GeyserMC",
          "module": "MCAuthLib",
          "version": {
            "requires": "d9d773e5d50327c33898c65cd545a4f6ef3ba1b5"
          },
          "excludes": [
            {
              "group": "org.lwjgl.lwjgl",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "retrocommands-0.7.3+gen2.jar",
          "url": "retrocommands-0.7.3+gen2.jar",
          "size": 127540,
          "sha512": "f8e528be9544b1d4d428fab5ef0c5b2489dcd000a5a8ac38b78946fc156f997f644d600b27a4e0393bb8dcc6896d50bbc5752ecfeb188033c76f2e73e7f18535",
          "sha256": "d32275c41ff4b3ad95c3b92e95c89dfb84bca40041b472a9cc0ca6c4121c41d3",
          "sha1": "7c1b21706e0f3166450516794d2290799cba5ae5",
          "md5": "c5936fb9a04b3cd54db7aa4f610aed37"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "retrocommands-0.7.3+gen2-sources.jar",
          "url": "retrocommands-0.7.3+gen2-sources.jar",
          "size": 67287,
          "sha512": "3f19e08a50401c71564aa0502110a4a03ee0318a332b546ea760ce395fd7b2cf37501ae227778681773e9ac2e3a425f230b87772fd371a6bd5abc57f5f20ba73",
          "sha256": "32e7317ad6a3f99deba2e5b48861b78bdcfebf12d3c892f2122f9ed3121b4f73",
          "sha1": "51eae51513b28bef7b39779a8ff6f9749860f0f1",
          "md5": "9c726c3de401e455fcd4012a14ed9213"
        }
      ]
    }
  ]
}
